libwm_srcs = files(
    'wm_system.c',
    'wm_sync.c',
    'wm_standard.c',
    'wm_mp.c',
    'wm_dcf.c',
    'wm_ds.c',
    'wm_ks.c',
    'wm_etc.c'
)

if(sdk_version_major == 5)
    libwm_srcs += files(
        'nwm_cmd.c',
        'nwm_end.c',
        'nwm_init.c',
        'nwm_passphrase.c',
        'nwm_system.c'
    )
endif

libwm_arm7_srcs = files('wm_sp.c')
