libspi_srcs = files(
    'tp.c',
    'mic.c',
    'pm.c'
)

if(sdk_version_major == 5)
    libspi_srcs += files(
        'micex.c'
    )
endif

libspi_arm7_srcs = files(
    'spi_arm7.c',
    'tp_arm7.c',
    'tp_arm7_2.c',
    'pm_arm7.c',
    'pm_arm7_2.c',
    'mic_arm7.c',
    'mic_arm7_2.c',
)
